---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: azorica-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - source: assets/fonts
        destination: /usr/share/fonts/mscorefonts # copies basic MS fonts to the system fonts folder
        
  - type: dnf
    repos:
      cleanup: true
      nonfree: rpmfusion
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      copr:
        - atim/starship
        - sneexy/zen-browser

    # swap Fedora's ffmpeg-free for RPM Fusion's full ffmpeg (declare once here)
    replace:
      - from-repo: rpmfusion-free
        allow-erasing: true
        packages:
          - ffmpeg-free
          - ffmpeg

    optfix:
      - zen

    install:
      skip-unavailable: true
      packages:
        - starship
        - gh
        - unrar
        - p7zip 
        - p7zip-plugins
        - s-tui
        - micro
        - fastfetch
        - hyfetch
        - tlp
        - thermald

        # --- Multimedia / Codecs / VA-API ---
        # FFmpeg libs (ffmpeg itself comes via replace: above)
        - ffmpeg-libs
        # GStreamer plugin stacks from RPM Fusion
        - gstreamer1-plugins-good
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-ugly
        - gstreamer1-plugin-libav
        # VA-API (Intel iHD for T480 / UHD 620)
        - gstreamer1-vaapi
        - intel-media-driver
        - libva-utils
        # OpenH264 (WebRTC/Firefox/GStreamer)
        - mozilla-openh264
        - gstreamer1-plugin-openh264

        # GUI Apps
        - zen-browser
        - xournalpp
        - gimp
        - inkscape
        - celluloid
        - handbrake
        - handbrake-gui

        # Gnome Apps
        - gnome-font-viewer
        - loupe
        - decibels
        - evince
        - gnome-contacts
        - gnome-calendar
        - gnome-calculator
        - gnome-weather
        - gnome-tweaks

        # VS Code
        - repo: vscode-yum
          packages:
            - code

    remove:
      packages:
        - tuned
        - tuned-ppd

    group-install:
      with-optional: false
      packages:
        - virtualization

  - type: default-flatpaks
    configurations:
    - notify: false
      scope: system
      install:
        - md.obsidian.Obsidian
        - com.github.huluti.Curtail
        - de.haeckerfelix.Shortwave
        - org.gnome.Podcasts
        - io.missioncenter.MissionCenter
        - com.mattjakeman.ExtensionManager

  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - AppIndicator and KStatusNotifierItem Support
      - Blur my Shell
      - Dash to Dock
      - GSConnect
      - Hot Edge 
      - Night Theme Switcher
      - Tiling Shell

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - CascadiaCode
        - CascadiaMono
        - SourceCodePro
        - Iosevka
        - JetBrainsMono
      google-fonts:
        - Open Sans
        
  - type: kargs
    kargs:
      - i915.enable_guc=2

  - type: script
    scripts:
      - image_name.sh

  - type: signing
