---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: azorica-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: rpmfusion
      copr:
        - atim/starship
    replace:
      - from-repo: nonfree
        allow-erasing: true
        packages:
        - old: ffmpeg-free
          new: ffmpeg
    install:
     packages:
        - micro
        - starship
        - fastfetch
        - hyfetch
        - thermald
        - tlp
        - gnome-tweaks
        - intel-media-driver
        - ffmpeg-libs 
        - gstreamer1-libav 
        - gstreamer1-plugin-openh264 
        - gstreamer1-plugins-bad-freeworld 
        - gstreamer1-plugins-ugly
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - tuned
        - tuned-ppd
    group-install:
      with-optional: true # install optional packages from group
      packages:
        - virtualization
        # - development-tools

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - app.zen_browser.zen
        - com.mattjakeman.ExtensionManager
        - org.gnome.Loupe
        - md.obsidian.Obsidian
        - de.haeckerfelix.Shortwave
        - io.github.celluloid_player.Celluloid
        - fr.handbrake.ghb
        - fr.handbrake.ghb.Plugin.IntelMediaSDK
      remove:
        - org.gnome.Extensions
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: kargs
    kargs:
      - i915.enable_guc=2

  - type: script
    scripts:
      - image_name.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

