---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: azorica-os
description: Personal atomic Fedora image based on Silverblue.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      nonfree: negativo17
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      copr:
        - atim/starship

    # Swap Fedora's ffmpeg-free for negativo17's full ffmpeg.
    # Repo id for negativo17 multimedia is "fedora-multimedia".
    replace:
      - from-repo: fedora-multimedia
        allow-erasing: true
        packages:
          - ffmpeg-free
          - ffmpeg

    install:
      skip-unavailable: true
      packages:
        - starship
        - gh
        - unrar
        - p7zip
        - p7zip-plugins
        - s-tui
        - micro
        - fastfetch
        - hyfetch
        - tlp
        - thermald

        # --- Multimedia / Codecs / VA-API (negativo17) ---
        - ffmpeg-libs
        - gstreamer1-plugins-good
        - gstreamer1-plugins-bad
        - gstreamer1-plugins-ugly
        - gstreamer1-plugin-libav
        - gstreamer1-vaapi
        - intel-media-driver
        - libva-utils
        # OpenH264 is provided in negativo17; do NOT enable Fedora's Cisco repo
        - mozilla-openh264
        - gstreamer1-plugin-openh264

        # GNOME Apps
        - gnome-font-viewer
        - loupe
        - decibels
        - evince
        - gnome-contacts
        - gnome-calendar
        - gnome-calculator
        - gnome-weather
        - gnome-tweaks

        # VS Code
        - repo: vscode-yum
          packages:
            - code

    remove:
      packages:
        - tuned
        - tuned-ppd

    group-install:
      with-optional: false
      packages:
        - virtualization

  - type: default-flatpaks
    configurations:
    - notify: true
      scope: system
      install:
        - md.obsidian.Obsidian
        - com.github.xournalpp.xournalpp
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - com.github.huluti.Curtail
        - fr.handbrake.ghb
        - io.github.celluloid_player.Celluloid
        - de.haeckerfelix.Shortwave
        - org.gnome.Podcasts
        - io.missioncenter.MissionCenter
        - com.mattjakeman.ExtensionManager

  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - AppIndicator and KStatusNotifierItem Support
      - Blur my Shell
      - Dash to Dock
      - GSConnect
      - Hot Edge
      - Night Theme Switcher
      - Tiling Shell
      - Workspaces indicator by open apps

  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaCode
        - CascadiaMono
        - SourceCodePro
        - Iosevka
        - JetBrainsMono
      google-fonts:
        - Open Sans

  - type: kargs
    kargs:
      - i915.enable_guc=2

  - type: script
    scripts:
      - image_name.sh

  - type: signing
