---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: azorica-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      #- source: assets/fonts
      #  destination: /usr/share/fonts/mscorefonts # copies basic MS fonts to the system fonts folder
        
  - type: dnf
    repos:
      cleanup: true
      nonfree: rpmfusion
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      copr:
        - atim/starship
        - sneexy/zen-browser
    optfix:
      - zen
    install:
      packages:
        - starship
        - gh   
        - unrar
        - p7zip 
        - p7zip-plugins
        - s-tui
        - micro
        - fastfetch
        - hyfetch
        - tlp
        - thermald
        - gnome-tweaks
        - intel-media-driver
        - gstreamer1-plugin-openh264 
        - gstreamer1-plugins-bad-freeworld 
        - gstreamer1-plugins-ugly
        # GUI Apps
        - zen-browser
        - xournalpp
        - gimp
        - inkscape
        - celluloid
        - handbrake
        - handbrake-gui
        # Gnome Apps
        - gnome-font-viewer
        - loupe
        - decibels
        - evince
        - gnome-contacts
        - gnome-calendar
        - gnome-calculator
        - gnome-weather
        # VS Code
        - repo: vscode-yum
          packages:
            - code
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        # - firefox
        # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - tuned
        - tuned-ppd
    group-install:
      with-optional: false # install optional packages from group
      packages:
        - virtualization

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        # - org.mozilla.firefox
        # - app.zen_browser.zen
        - md.obsidian.Obsidian
        - de.haeckerfelix.Shortwave
        - io.missioncenter.MissionCenter
        - com.mattjakeman.ExtensionManager
        # - io.github.celluloid_player.Celluloid
        # - fr.handbrake.ghb
        # - fr.handbrake.ghb.Plugin.IntelMediaSDK
        # - com.github.xournalpp.xournalpp
        # - org.gnome.font-viewer
        # - org.gnome.Loupe
        # - org.gnome.Decibels
        # - org.gnome.Evince
        # - org.gnome.Contacts
        # - org.gnome.Calendar
        # - org.gnome.Calculator
        # - org.gnome.Weather
      remove:
        - org.gnome.Extensions
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - AppIndicator and KStatusNotifierItem Support
      - Blur my Shell
      - Dash to Dock
      - GSConnect
      - Night Theme Switcher

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - CascadiaCode
        - CascadiaMono
        - SourceCodePro
        - Iosevka
        - JetBrainsMono
      google-fonts:
        - Open Sans
        
  - type: kargs
    kargs:
      - i915.enable_guc=2

  - type: script
    scripts:
      - image_name.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

